version: 0.2
phases:
  install:
    commands:
      - echo "No dependencies to install for HTML, CSS, and JS"
  build:
    commands:
      - echo "Build step - Just packaging static files"
  post_build:
    commands:
      - aws s3 sync . s3://react-app-bucket1212 --delete
artifacts:
  files:
    - '**/*'
